homepage/urls.py
from django.urls import path
from . import views


app_name = 'homepage'

urlpatterns = [
    path('', views.pertama, name='pertama'),
    path('about/', views.about, name='about'),
    path('experience/', views.experience, name='experience'),
    path('contact/', views.kontak, name='kontak'),
    path('bonus/', views.bonus, name='bonus'),
    path('schedule/', views.schedule, name='schedule'),
    path('schedule/create', views.schedule_create, name='schedule_create'),
    path('schedule/delete', views.schedule_delete, name='schedule_delete'),
    path('schedule/hilang/<int:id>', views.schedule_hilang, name='schedule_hilang'),



]

story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
from datetime import datetime

# Create your models here.


class Schedule(models.Model):

    activity = models.CharField(max_length=30)
    date = models.DateTimeField(default=datetime.now)
    time = models.TimeField()
    place = models.CharField(max_length=20)
    category = models.CharField(max_length=20)

    def __str__(self):
        return self.activity

homepage/forms.py
from django import forms
from .models import Schedule


class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ['activity', 'date', 'time', 'place', 'category']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

homepage/views.py
from django.shortcuts import render, redirect
from .models import Schedule
from . import forms


# Create your views here.
def pertama(request):
    return render(request,'PPW.html')

def about(request):
    return render(request,'About.html')

def experience(request):
    return render(request,'Experience.html')

def kontak(request):
    return render(request,'Contact.html')

def bonus(request):
    return render(request,'Bonus.html')

def schedule(request):
    schedules = Schedule.objects.all().order_by('date')
    return render(request, 'schedule.html', {'schedules': schedules})

def schedule_create(request):
    if request.method == 'POST':
        form = forms.ScheduleForm(request.POST)
        if form.is_valid():
            form.save()
            form = forms.ScheduleForm()


    else:
        form = forms.ScheduleForm()
    return render(request, 'schedule_create.html', {'form': form})


def schedule_delete(request):
	Schedule.objects.all().delete()
	return render(request, "schedule.html")



def schedule_hilang(request, id):
    schedule = Schedule.objects.get(id=id)
    schedule.delete()
    schedules = Schedule.objects.all()
    return render(request, 'schedule.html', {'schedules': schedules})

homepage/templates/About.html
            {% extends 'blog/base.html' %}
            {% load static %}
            {% block content %}
            <section>
                    <div id="main7" class="jumbotron">
                            <div class="row" id="rowdes">
                                <div class="container photoSkills col-sm-6" id="textInfo">
                                        
                                        <img src="{% static 'images/anjas.jpg' %}" alt="Nandi's Photo" id="profilePicture"  >
                                    <br>

                                    <div id="myskil">
                                            <h1 id="deskripsi"><i>MY SKILLS : </i></h1>
                                            <ul>
                                                <li id="jenis">Programming</li>
                                                <li id="jenis">Public Speaking "MC"</li>
                                                <li id="jenis">Editing Video</li>
                                                <li id="jenis">Processing Data on Excel</li>

                                            </ul>
                                           
                                    </div>
                                    


                                </div>
                           
                                <div class="container photoSkills col-sm-6" id="photoslang">
                                        <div>
                                                <form>
                                                        <fieldset id="fieldsetah" >
                                                            <legend id="deskripsi"><i>My Description</i></legend>
                                                                <table>
                                                                        <tr>
                                                                            <td>
                                                                                <b>Name : Muhammad Destara Syanandi</b> 
                                                                            </td>
                                                                            
                                                                        </tr>
                                                                        <tr>
                                                                                <td>
                                                                                        <b>NPM : 1806186856  
                                                                                        </b> 
                                                                                </td>
                                                                                
                                                                            </tr>
                                                                        <tr>
                                                                                <td>
                                                                                        <b>Umur : 18 Tahun  
                                                                                        </b> 
                                                                                </td>
                                                                                
                                                                            </tr>
                                                                        <tr>
                                                                                <td>
                                                                                        <b>Gender :Laki</b> 
                                                                                </td>
                                                                                
                                                                            </tr> 
                                                                        <tr>
                                                                                <td>
                                                                                        <b>Email :destarasyanando@gmail.com</b> 
                                                                                </td>
                                                                                
                                                                                </tr>    
                                                                        
                                                                       <tr>
                                                                            <td>
                                                                                <b>Deskripsi Singkat : </b>
                                                                                <p id="pajah">“Hello , my name is Muhammad Destara syanandi. <br> Im a  Computer 
                                                                                        Science Student at Universitas Indonesia. <br>
                                                                                        My passion si programming and public speaking.”
                                                                                </p>
                                                                            </td>
                                    
                                                                       </tr>
                                                                    </table>
                                                        </fieldset>
                                                    
                                                </form>
                                        </div>
                                        <img src="{% static 'images/keren.jpg' %}" alt="mic" id="mic">
                                        <img src="{% static 'images/asik2.jpg' %}" alt="coding" id="coding2">

                                        <br>


                                        <img src="{% static 'images/aselole.jpg' %}" alt="skill" id="skillfoto">
                
                                </div>
                            </div>  
                        </div>
            </section>
            
            {% endblock %}


            
       
               
        
                    
                    
        
        
        
        
               
        

homepage/templates/Bonus.html
    {% extends 'blog/base.html' %}
    {% load static %}
    {% block content %}
    <section class="main3">
            <div class="container text-center">
                    <h3 id="favoritefont">
                            My Favorite Movies
                    </h3>
                    
                    
            </div>                       
        </section>
         <section>
                    <div id="main10" class="jumbotron">
                            <div class="row" id="rowdes">
                                <div class="container photoSkills col-sm-6" id="textInfo">
                                    <div>
                                            <img src="{% static 'images/inception.jpg' %}" alt="inception" id="fotomovies">
                                            <br>
                                            <br>
                                            <img src="{% static 'images/shaw.jpg' %}" id="foto2movies">
                                    </div>
                                
                            
                                        

                                    
                                    


                                </div>
                                
                           
                                <div class="container photoSkills col-sm-6" id="photoslang">
                                        <div>
                                                <img src="{% static 'images/Inter.jpg' %}" alt="intersterllar" id="foto3movies">
                                                <br>
                                                <br>
                                                <img src="{% static 'images/fight.jpg' %}" alt="fightClub" id="foto4movies"> 
                                            
                                        </div>
                                        

                
                                </div>
                            </div>  
                        </div>
            </section>

            {% endblock %}

   
        
                
        
            
   
        
                
                

            
            
       
            
        
                    
                    
        
        
        
        
               
      

homepage/templates/Contact.html
    {% extends 'blog/base.html' %}
    {% load static %}
    {% block content %}
    <section class="main3">
            <div class="container text-center">
                    <h3 id="JudulContact">
                            Let’s Get 
                    </h3>
                    <br>
                    <br>
                    <br>
                    <h1 id="JudulContact2">
                            Connected!
                    </h1>
            </div>                       
        </section>
        <section class="main5">
                <div class="container text-center">                      
                    <a href="https://www.instagram.com/destarass/"><img src="{% static 'images/Linkedin.jpg' %}" alt="Linkedin" id="socmed">  </a>
                    <a href="https://www.instagram.com/destarass/"><img src="{% static 'images/download.png' %}" alt="Photo of instagram" id="socmed" ></a>                                   
                    <a href="https://twitter.com/Destara57093854"><img src="{% static 'images/twitter.jpg' %}" alt="Photo of twitter" id="socmed" ></a>
                </div>                       
            </section>
    {% endblock %}
   
        
                
        
            
   
        
                
                

            
            
       
            
        
                    
                    
        
        
        
        
               

homepage/templates/Experience.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
    <section class="main2">
            <div class="container text-center">
                    <p class="titleexperience" >MY EXPERIENCE <br>IN </p>
                    <img src="{% static 'images/110px-Makara_FASILKOMUI.png' %}" alt="makaraui" id="makarafasilkom">  
                    <br> 
                    <img src="{% static 'images/cgt.jpg' %}" alt="Photo of cgt" id="cgt" >
                    <img src="{% static 'images/compfest.jpg' %}" alt="Photo of compfest" id="cmp" >
                    <img src="{% static 'images/pmb.jpg' %}" alt="Photo of pmb" id="pmb" class="codelang rightie upper">
            </div>                       
        </section>

 {% endblock %}

   
        
                
        
            
   
        
                
                

            
            
       
            
        
                    
                    
        
        
        
        
               
      

homepage/templates/PPW.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
    <section class="main">
        <div class="container text-center">
                <p class="promo-title" >HELLO,I’m Nandi!  </p>
                <h2> WELCOME TO</h2>
                <h2 >My WEB Profile</h2>
                <a href="{% url 'homepage:about' %}" class="transparent_btn">Click ME!</a>
        </div>
            
    </section>

 {% endblock %}

homepage/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>AboutMe</title>
</head>
<body id="body2" >
        <section id="header">
                <div class="container-fluid">
                    <nav class="navbar navbar-expand-lg navbar-dark">
        
                            <div class="container-fluid">
                                    <a href="{% url 'homepage:pertama' %}" class="navbar-brand">N&I</a>
                                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                    aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                <ul class="navbar-nav ml-auto">
                                    <li class="nav-item  ">
                                        <a href="{% url 'homepage:pertama' %}" class="nav-link">Home</a>
                                    </li>
                                    <li class="nav-item   ">
                                        <a href="{% url 'homepage:about' %}" class="nav-link">About</a>
                                    </li>
                                    <li class="nav-item ">
                                        <a href="{% url 'homepage:experience' %}" class="nav-link">Experience</a>
                                    </li>
                                    <li class="nav-item ">
                                        <a href="{% url 'homepage:kontak' %}" class="nav-link">Contact</a>
                                    </li>
                                    <li class="nav-item   ">
                                            <a href="{% url 'homepage:bonus' %}" class="nav-link">Bonus</a>
                                    </li>
                                    <li class="nav-item   ">
                                        <a href="{% url 'homepage:schedule' %}" class="nav-link">Schedule</a>
                                    </li>
                                </ul>
                            </div>
                            </div>
                    </nav> 
                </div>
        
            </section>
            {% block content %}
            {% endblock %}


            <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        
        
</body>
</html>

homepage/templates/schedule.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

<div class="row justify-content-center align-items-center row3" id="form1">
                <h1 class="formText" id="favoritefont">To-Do List</h1>
</div>

<div class="row justify-content-center align-items-center row2 form" id="form2">
    <div class="col-md-4">
        <div class="container backforms" >
            <div class="article" >
                 <a href="{% url 'homepage:schedule' %}"></a>
                 <div class="article">
                 <div class="row">
                    {% for schedule in schedules %}
                        <div class="col-sm-5 text-center isinya1" >
                            <div class="wrap-group">

                                    <h2 id="Judul">{{ schedule.activity }}</h2>
                                    <div class="border">
                                            <p id="isi">{{ schedule.date.date }}</p>
                                            <p id="isi">{{ schedule.time}}</p>
                                            <p id="isi">{{ schedule.place }}</p>
                                            <p id="isi">{{ schedule.category }}</p>
                                            <br>
                                            <a href="{% url 'homepage:schedule_hilang' id=schedule.id %}"><button type ="button" class="btn btn-danger btn-sm mt-3">Delete</button></a>
                                            
                                             
                                    </div>
                                    
                            </div>
                            

                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        </div>
    </div>
</div>



    <div class="row justify-content-center align-items-center row2 buttonadd">
        <div class = 'col-md-2'>
            <div class = 'form-group'>
                <a href="{% url 'homepage:schedule_delete' %}"><button type="button" class= "btn btn-secondary btn-lg btn-sm">Clear</button></a>
                <a href="{% url 'homepage:schedule_create' %}"><button type="button" class= "btn btn-secondary btn-lg btn-sm">Create</button></a>
            </div>
        </div>
    </div>

 {% endblock %}

homepage/templates/schedule_create.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}



<div class="row justify-content-center align-items-center row3 form" id = "form1">
    <div class="container backforms">
        <form class="css" action="{% url 'homepage:schedule_create' %}" method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-sm-1"></div>
                    <div class="form-group col-sm-10" id="isibox">
                        {% for fields in form %}
                            {{ fields.label_tag }}
                            <br>
                            {{ fields }}
                        {% endfor %}
                    </div>
                </div>
                <div class="form-row">  
                <div class="col-sm-1"></div>
                <input type="submit" class="btn btn-primary " value="Add">
            </form>
            </div>
        </div>
        </div>
        </div>


{% endblock %}